import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar/Navbar";
import { AppProvider } from "@/context/AppContext";
import Loader from "@/components/Loader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export const viewTranistion: Metadata = {
  title: "view-tranistion",
  description: "same-origin",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`h-svh relative bg-light dark:bg-medium dark:text-white text-stone-700 ${inter.className}`}
      >
        <AppProvider>
          <Loader />
          <Navbar />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
