import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { AppProvider } from "@/context/AppContext";
import Loader from "@/components/Loader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`h-svh relative bg-slate-200 dark:bg-medium dark:text-white text-stone-700 ${inter.className}`}
      >
        <AppProvider>
          <Loader />
          <Navbar />
          {children}
        </AppProvider>
      </body>
    </html>
  );
}
